apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage-test
spec:
  hosts:
    - "*"
  gateways:
    - bookinfo-gateway
  http:
    - match:
      - uri:
          exact: /productpage
      - uri:
          prefix: /static
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products     
  route:
  - destination:
      host: productpage
      subset: v2
      port:
        number: 9080
      weight: 50
  - destination:
        host: productpage
        subset: v2
        port:
          number: 9080
        weight: 50